### ISSUE TITLE
could not change task mode

### ISSUE THREAD

**Issue by lsylsy0516** [Arena-Rosnav/arena-rosnav#120]
when i git pull the latest code, I found that there are no task_mode in arena_bringup.launch ,and the task always goes in a random mode

**Comment by voshch** [comment]
Hi, the `task_mode` argument has been split into `tm_robots` and `tm_obstacles`.
Please refer to [the current documentation](https://arena-rosnav.readthedocs.io/en/latest/user_guides/task_modes/) for a detailed description.
