### ISSUE TITLE
namespace error

### ISSUE THREAD

**Issue by sunnyhello3696** [Arena-Rosnav/arena-rosnav#121]
20240117 
The new version has namespace issues:
The new task_generator_node.py has a namespace confusion that causes the program to run incorrectly.
I suspect this may be caused by a change in the Namespace class in the file src/arena-rosnav/task_generator/task_generator/shared.py.
```
@property
def simulation_ns(self) -> Namespace:
    ns_components = self.split("/")
    return Namespace(f"/{ns_components[1]}") if len(ns_components) > 2 else self

@property
def robot_ns(self) -> Namespace:
    ns_components = self.split("/")
    return Namespace(f"/{ns_components[2]}") if len(ns_components) > 2 else self
```
```
@property
def simulation_ns(self) -> Namespace:
    return Namespace(self.split("/")[0])

@property
def robot_ns(self) -> Namespace:
    return Namespace(self.split("/")[1])
```

**Comment by voshch** [comment]
Hi, was your issue resolved by 31bb96398992714686b891fb6cc3c89fe47aa370?
Best Regards
