### ISSUE TITLE
Multiple robots launch

### ISSUE THREAD

**Issue by YumengXiu** [Arena-Rosnav/arena-rosnav#181]
Hi, thank you very much for the great work.
I'd like to ask how to launch multiple robots in the simulator, is there any example of loading robot_set_up file？
Right now I can only launch a single robot and his local_planner with arguments, Thanks!

**Comment by voshch** [comment]
Hey, follow the [schema](https://github.com/Arena-Rosnav/arena-rosnav/blob/master/arena_bringup/configs/robot_setup/SCHEMA.yaml) to define robots.
You can try out one of the existing set-ups using `robot_setup_file:=demo.yaml`.
