### ISSUE TITLE
Error occurred: pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.

### ISSUE THREAD

**Issue by zzzzzziyi** [Arena-Rosnav/arena-rosnav#196]
Hi author, thank you for your fantastic work. When I run the command "**curl https://raw.githubusercontent.com/Arena-Rosnav/arena-rosnav/master/install2.sh | bash**" in automatic installation, the following error occurred "**pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.**". 

I am wondering if one of the possible reasons is because the poetry.lock is not updated together with pyproject.toml? Would appreaciate for your prompt response! Thank you!

![Screenshot from 2024-07-02 20-37-57](https://github.com/Arena-Rosnav/arena-rosnav/assets/91865986/7df485a6-ce81-4a73-9fd2-3d5c17f7a805)

**Comment by voshch** [comment]
Delete the poertry.lock in src/arena/arena-rosnav. We will address this in an update ASAP.

**Comment by voshch** [comment]
https://github.com/Arena-Rosnav/arena-rosnav/pull/197
