### ISSUE TITLE
where is rosbag files? in "arena-rosnav"

### ISSUE THREAD

**Issue by CAI23sbP** [Arena-Rosnav/arena-rosnav#37]
Hi ReykCS.
 i saw your code in arena ros-nav(https://github.com/ignc-research/arena-rosnav/tree/local_planner_subgoalmode/arena_navigation/arena_local_planner/evaluation). 
In that read.me file, it said to me that "More information about how to record can be found [here] Some **example** [rosbags]are located in rosbags.". So i clicked that links ([here],[rosbags]) , but there was no site or folder something else. 
Can i take your information about that?

**Comment by ReykCS** [comment]
Hey,
we dropped support for rosbag files and record necessary data with our [arena-evaluation](https://github.com/Arena-Rosnav/arena-evaluation) package. Just set the "record_data:=true" argument on startup and your robots should be recorded.

**Comment by CAI23sbP** [comment]
Thank you for your quick answer ReykCS.

**Comment by ReykCS** [comment]
Continuing here https://github.com/Arena-Rosnav/arena-rosnav/issues/38
