### ISSUE TITLE
About arena-tool git

### ISSUE THREAD

**Issue by CAI23sbP** [Arena-Rosnav/arena-rosnav#56]
Hi @ReykCS ! long time no  see. :)
i researched arena-tool for add Pedsim_interaction_obstacle(static obstacle) to add in my scenario. But there was not able to add interaction_obstacle. Just TODO... 
Could you tell me that whether  [this repo  ](https://github.com/Arena-Rosnav/arena-tools) have finished or not finished yet ?

**Comment by linhdoan8** [comment]
Hey, we are dismissing arena-tools and instead use [arena-web](app.arena-web.com) to create scenarios. However, due to a new scenario structure with more functionalities, the webapp has to be updated to the new format which will happen in the next weeks.
