### ISSUE TITLE
ImportError: cannot import name 'get_predefined_task' from 'task_generator.tasks.utils' (/root/autodl-tmp/arena_ws/src/arena-rosnav/task_generator/task_generator/tasks/utils.py)

### ISSUE THREAD

**Issue by sunnyhello369** [Arena-Rosnav/arena-rosnav#75]
2323.11.01 new version run error?

python training/scripts/train_agent.py
Traceback (most recent call last):
  File "training/scripts/train_agent.py", line 10, in <module>
    from tools.env_utils import init_envs
  File "/root/autodl-tmp/arena_ws/src/arena-rosnav/training/tools/env_utils.py", line 16, in <module>
    from rl_utils.envs.flatland_gym_env import (
  File "/root/autodl-tmp/arena_ws/src/arena-rosnav/utils/misc/rl_utils/rl_utils/envs/flatland_gym_env.py", line 15, in <module>
    from task_generator.tasks.utils import get_predefined_task
ImportError: cannot import name 'get_predefined_task' from 'task_generator.tasks.utils' (/root/autodl-tmp/arena_ws/src/arena-rosnav/task_generator/task_generator/tasks/utils.py)

**Comment by linhdoan8** [comment]
Hi, the training pipeline is currently being adapted to our new task generator. Therefore, it is not working. The fixes will be pushed until next Wednesday.

**Comment by sunnyhello369** [comment]
> Hi, the training pipeline is currently being adapted to our new task generator. Therefore, it is not working. The fixes will be pushed until next Wednesday.

ok，thanks

**Comment by sunnyhello369** [comment]
Dear developers
The above problem seems to be unresolved and fails to compile with the catkin_make command.
