### ISSUE TITLE
Issue with Pedestrian Waypoints in scenarios/default.json:people are just circling around instead of walking to the set waypoints

### ISSUE THREAD

**Issue by lsylsy0516** [Arena-Rosnav/arena-rosnav#88]
### Issue Description
I am currently running the arena-rosnav simulation package, and I have encountered an issue with the pedestrian waypoints defined in the `arena-rosnav/arena_bringup/configs/scenarios/default.json` file.

### Problem
The waypoints set for pedestrians in the `scenarios/default.json` file are not followed as expected during simulation. Instead of following the specified waypoints, pedestrians seem to rotate around the spawn point (`pos`), creating a circular motion.

### Steps to Reproduce
1. Run the arena-rosnav simulation with the provided `scenarios/default.json`:`roslaunch arena_bringup start_arena.launch simulator:=gazebo task_mode:=scenario model:=jackal map_file:=map_empty pedsim_waypoint_plugin:=spinny`

2. Observe the behavior of pedestrians in relation to the defined waypoints.

### Configuration Details
```json
// Relevant snippet from scenarios/default.json
            {
                "name": "1",
                "id": 0,
                "pos": [
                    14.0,
                    2.0,
                    0.0
                ],
                "type": "adult",
                "model": "actor1",
                "number_of_peds": 1,
                "vmax": 0.3,
                "start_up_mode": "default",
                "wait_time": 0.0,
                "trigger_zone_radius": 0.0,
                "chatting_probability": 0.0,
                "tell_story_probability": 0.0,
                "group_talking_probability": 0.0,
                "talking_and_walking_probability": 0.0,
                "requesting_service_probability": 0.0,
                "requesting_guide_probability": 0.0,
                "requesting_follower_probability": 0.0,
                "max_talking_distance": 5.0,
                "max_servicing_radius": 5.0,
                "talking_base_time": 10.0,
                "tell_story_base_time": 0.0,
                "group_talking_base_time": 10.0,
                "talking_and_walking_base_time": 6.0,
                "receiving_service_base_time": 20.0,
                "requesting_service_base_time": 30.0,
                "force_factor_desired": 1.0,
                "force_factor_obstacle": 1.0,
                "force_factor_social": 5.0,
                "force_factor_robot": 5.0,
                "waypoints": [
                    [
                        1.0,
                        14.0,
                        0.0
                    ]
                ],
                "waypoint_mode": 1
            },

Environment

    Operating System: Ubuntu 20.04
    ROS Version: ROS Noetic
    arena-rosnav Version: master

**Comment by linhdoan8** [comment]
Hi, that because you used our spinny waypoint pluggin by specifying 

```pedsim_waypoint_plugin:=spinny```

This was just a demo plugin to showcase our waypoint manager. For normal behavior just delete this part in your command and the peds should move correctly. We are currently working on more realistic ped behavior, e.g. in future you can start different social force models with 

```pedsim_waypoint_plugin:=deepsocialforce```

**Comment by lsylsy0516** [comment]
thanks ,this really helped me a lot
